### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by IlCallo**
https://github.com/NetanelBasal/spectator/issues/83 and https://github.com/NetanelBasal/spectator/issues/84
Only updated dependencies for now.
I also removed package-lock, given that it seems to me that you're using yarn now and it was outdated.

Plop accepts a global `--force` option, but I'm not understanding how to make the parameter work inside the spectator-cli.

I am launching it like `node index.js`, dunno if it's the correct way to use it during development.

The "prompt if existing" feature seems not currently possible: https://github.com/amwmedia/node-plop/pull/50

You can either put a `force` option, which will override everything automatically and isn't a good idea, or pass by a `--force` parameter, which I don't understand how to pass by (I get a `nodejs\node.exe: bad option: --force`).

Ideas?

### CODE REVIEW

**Comment by IlCallo** [comment]
@NetanelBasal ping?

**Comment by NetanelBasal** [comment]
I missed that, sorry.

**Comment by NetanelBasal** [comment]
I think you should add the `force` property here: https://github.com/NetanelBasal/spectator-cli/blob/master/plopfile.js#L54

**Comment by IlCallo** [comment]
That would force the creation all the times, overriding existing files, it's not a good scenario.
I wanted to make the command work with the `--force` flag that you can set manually, but I'm unable to make the flag pass by to plop, it gives me `nodejs\node.exe: bad option: --force` error if I try `node index.js --force`.

Maybe for now it's ok to just merge the dependencies updates, I'll check how to make the `force` option work as I wanted.

**Comment by IlCallo** [comment]
Thanks for the merge, is there an ETA about when are you gonna release it?
On NPM registry latest version is still 0.1 and I could not find a @dev channel to try it out without a new release

**Comment by NetanelBasal** [comment]
Published. Thanks.

**Pull request merged**
